#!/usr/bin/env bash
# -*- coding: utf-8 -*-
#
# Copyright (C) 2021 Johnny Mariéthoz.
#
# Coons is free software; you can redistribute it and/or modify it under the
# terms of the MIT License; see LICENSE file for more details.

set -e

script_path=$(dirname "$0")
./"$script_path"/bootstrap

pipenv run invenio alembic upgrade
pipenv run invenio index init --force
